// Generated by CoffeeScript 1.7.1
var Parser, _;

_ = require('underscore');

Parser = {
  parsers: {},
  addParser: function(name, rule) {
    return this.parsers[name] = rule;
  },
  checkRule: function(name) {
    var rule;
    rule = this.parsers[name];
    if (typeof name === 'string' && rule && typeof rule.parse === 'function') {
      return true;
    }
    throw new Error(name + ' is not a complete rule. A complete rule must contain `parse` function.');
  },
  parse: function(obj, ruleset) {
    var key, rule, value;
    if (!obj) {
      return obj;
    }
    for (key in ruleset) {
      rule = ruleset[key];
      if ((value = obj[key]) != null) {
        obj[key] = this.parsers[rule].parse(value);
      }
    }
    return obj;
  }
};

Parser.addParser('binary', {
  parse: function(value) {
    if (/^(true|[1-9]+[0-9]*)$/i.test(value)) {
      return 1;
    } else {
      return 0;
    }
  }
});

module.exports = Parser;
